### ISSUE TITLE
이미지 상당수 오류

### ISSUE THREAD

**Issue by 36DB** [CirnoV/girlsfrontline-resources#1]
이미지 중 파일 자체가 깨진 이미지도 있고(6_2_D)
일부분만 존재하는 파일도 있습니다(33_2)

**Comment by CirnoV** [comment]
라이브러리 제작 때문에 바쁘기 때문에 리소스에 신경 쓸 시간이 없습니다. 일러스트는 UABE로 일러와 alpha 까지 추출하신 뒤,
포토샵 등으로 하나로 합쳐서 Pull Request 부탁드립니다.


현재까지 문제가 있는것으로 파악되는 일러스트 번호는 다음과 같습니다.

6, 12, 15, 16, 17, 18, 33, 36

2018. 2. 17. 오전 2:36에 "36DB" <notifications@github.com>님이 작성:

**Comment by 36DB** [comment]
어찌어찌 혼자서 고생하다가 알아냈습니다..
어쨌든 감사합니다!

**Comment by CirnoV** [comment]
해결되셨으면 다른분들도 사용할 수 있도록 PR 부탁드립니다. 감사합니다.

**Comment by 36DB** [comment]
https://github.com/36DB/girlsfrontline-resources/pull/1
PR했습니당

**Comment by CirnoV** [comment]
그쪽 말고 여기로 PR해주세요

**Comment by 36DB** [comment]
깃헙은 익숙치 않아서..잘 모르겠네요
권한이 없는거 같은데..

**Comment by CirnoV** [comment]
![1](https://user-images.githubusercontent.com/17797795/36376877-314a142c-15b8-11e8-9eb2-a2a80b839625.PNG)

![3](https://user-images.githubusercontent.com/17797795/36376879-318692b2-15b8-11e8-9736-c8001f4a2d9c.PNG)

![4](https://user-images.githubusercontent.com/17797795/36376880-31b4a558-15b8-11e8-9451-c646d38ad036.PNG)

대충 이런식으로 작성하시면 됩니다.
