### ISSUE TITLE
숙소 있는 spine 파일은 있나요?

### ISSUE THREAD

**Issue by kjm1922** [CirnoV/girlsfrontline-resources#2]
숙소 SD 모델링 파일이 필요한데 해당 파일들이 안보이는듯 하네요.

**Comment by CirnoV** [comment]
몇개월전 파일은 [gfSpinePiXi](https://github.com/cullus/gfSpinePiXi)에서 구할 수 있지만, 최근에 나온 스킨이나 인형 데이터는 [UABE](https://github.com/DerPopo/UABE)로 직접 추출하셔야 합니다.

**Comment by kjm1922** [comment]
확인 감사드립니다. [gf-spine-simulator](https://github.com/kjm1922/gf-spine-simulator) 에 적용 위해서 누락된 신규 데이터들 한번 적용해봐야 겠습니다.
